# _config.yml
title: Tuba Tech Dynamics
email: info@tubatechdynamics.com
description: "Empowering Non-Profits with Affordable Tech Solutions"
baseurl: ""
url: "https://tubatechdynamics.com/"
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed

# Google Analytics
google_analytics: UA-XXXXXXXXX-X

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock

sass:
  sass_dir: _sass
  style: compressed
  load_paths:
    - _sass
    - node_modules

include:
  - assets
